### ISSUE TITLE
Unable to view details of Subscription product in Shop catalog

### ISSUE THREAD

**Issue by cygnus8929** [leegarner-glfusion/shop#41]
I created a subscription product using the latest subscription plugin (0.2.3). In the configuration for the subscription plugin, I have the setting "Show in Shop product catalog?" set to "Yes". When visit the shop as a user (/shop/index.php), the product shows up. However, when I click on the "Details" link, I get a message "Item not found". 

I've traced this to a call to line 64 in details.php, specifically to the call to $P->hasAccess() on that line. Groups are checked in Product.classes.php in the hasAccess() method. I have the group set in the Subscription product to be "Logged In Users". The user is a member of that group. It appears that when the Shop plugin gets the details about the product from the Subscription product, the group information is not being transferred over. 

If I comment out the $P->hasAccess() call, the error goes away, but then I get a blank page (no details are shown).

FWIW, the product appears correctly in the Subscription product page (/subscription/index.php).

**Comment by leegarner** [comment]
Fixed in 8e5d63655c21862b61400abd485ab16d79451133, released with 1.1.2

**Comment by cygnus8929** [comment]
The fix referenced above fixes the item not found error message, but when I click on the "Details" button, I still get a blank page. 

I traced into Product.class.php @ line 1639. When I comment the following line, I can see the product details.
           ` 'weight'            => $this->weight + $this->Variant->getWeight(),`

I get a similar error when I attempt to view the details of an "Other/Virtual" product created in the Shop plugin itself.

**Comment by leegarner** [comment]
You're right, that's something that I found which didn't make it to 1.1.2. It's fixed in the current develop branch. For now you can keep that commented out. It'll be fixed in release 1.2.0 which I expect to have done by the end of the month.
